import React from 'react';
import { WalletProvider } from './contexts/WalletContext';
import Header from './components/layout/Header';
import { Box, Button, Container, Typography } from '@mui/material';
import { useWallet } from './hooks/useWallet';

// An example component that requires a signature
const Dashboard: React.FC = () => {
  const { publicKey, kit } = useWallet();

  const handleSign = async () => {
    if (!publicKey || !kit) {
      alert('Please connect your wallet first.');
      return;
    }

    try {
      // This is an example of signing a transaction XDR.
      // Replace with a real transaction generated by your app.
      const xdr = 'AAAAAgAAAAD...';
      const signedXdr = await kit.signTx({ xdr });
      console.log('Transaction signed successfully:', signedXdr);
      // You can now submit this signed transaction to the network.
    } catch (error) {
      // Requirement: Error handling for rejected signature requests
      console.error('Signature rejected by user:', error);
      alert('You rejected the signature request in your wallet.');
    }
  };

  return (
    <Box mt={4}>
      <Typography variant="h4" gutterBottom>
        Safe Dashboard
      </Typography>
      {publicKey ? (
        <Box>
          <Typography>Welcome! Your connected address is: {publicKey}</Typography>
          <Button variant="contained" onClick={handleSign} sx={{ mt: 2 }}>
            Sign Example Transaction
          </Button>
        </Box>
      ) : (
        // Requirement: Fallback for "Watch-only" mode
        <Typography>
          Connect your wallet to manage your safe, or continue in watch-only mode to view public information.
        </Typography>
      )}
    </Box>
  );
};

const App: React.FC = () => {
  return (
    <WalletProvider>
      <Header />
      <Container>
        <Dashboard />
      </Container>
    </WalletProvider>
  );
};

export default App;